[workspace]
members = [
    "alpkit",
    "apk-inspect",
    "schema-gen",
]
default-members = [
    "alpkit",
    "apk-inspect",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
